services:
  application-service:
    build: ./backend/application-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://application-postgres:5432/postgres
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8003:8080"
      - "50008:50005"
    depends_on:
      - application-postgres
  application-postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  profile-service:
    build: ./backend/profile-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://profile-postgres:5432/postgres
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8002:8080"
      - "50007:50005"
    depends_on:
      - profile-postgres
  profile-postgres:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  vacancy-service:
    build: ./backend/vacancy-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://vacancy-postgres:5432/postgres
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8001:8080"
      - "50006:50005"
    depends_on:
      - vacancy-postgres
  vacancy-postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  auth-service:
    build: ./backend/auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/postgres
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8080"
      - "50005:50005"
    depends_on:
      - auth-postgres
      - profile-service
  auth-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}