version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - your_kafka_server=your_kafka_server
      - your_consumer_group=your_consumer_group
      - your_topic=your_topic
      - your_telegram_bot_token=your_telegram_bot_token
      - user_chat_id=user_chat_id
    restart: always
